import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

export default defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "next-env.d.ts",
    "src/wasm/pkg/**", // generated by wasm-pack
    "dna-cipher/target/**",
    "public/**",
    "playwright-report/**",
    "test-results/**",
  ]),
  {
    // Security posture (see README "Security"): no dynamic code, no HTML injection,
    // and no network primitives anywhere in first-party code.
    rules: {
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "react/no-danger": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "no-restricted-globals": [
        "error",
        { name: "fetch", message: "The app makes no network calls." },
        { name: "XMLHttpRequest", message: "The app makes no network calls." },
        { name: "WebSocket", message: "The app makes no network calls." },
        { name: "EventSource", message: "The app makes no network calls." },
      ],
      "no-restricted-properties": [
        "error",
        {
          object: "navigator",
          property: "sendBeacon",
          message: "The app makes no network calls.",
        },
      ],
    },
  },
  {
    // Node-side tooling and e2e tests legitimately use these.
    files: ["scripts/**", "e2e/**", "*.config.*"],
    rules: { "no-restricted-globals": "off" },
  },
]);
